name: Build and Deploy

on:
  push:
    branches: [ '*' ]

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        npm ci
        npm run build --if-present

    - name: Convert OpenAPI json to markdown
      run: node widdershins.js
        
    - name: Install mkdocs using Pip
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs

    - name: Deploy mkdocs site
      run: mkdocs serve
