name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Convert OpenAPI json to markdown
      run: node widdershins.js
      
    - uses: actions/checkout@v2
    - name: Install mkdocs using Pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install mkdocs with Pip
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
    
    - name: Deploy mkdocs site
      run: mkdocs serve