name: Build and Deploy

on:
  push:
    branches: [ '*' ]

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Test
      uses: actions/setup-node@v3
      with:
        node-version: '16'
      run: |
        npm ci
        npm run build --if-present

    - name: Convert OpenAPI json to markdown
      run: node widdershins.js
        
    - name: Install mkdocs using Pip
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs

    - name: Deploy mkdocs site
      run: mkdocs serve
